In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mymodels
import tensorflow as tf
from tensorflow.keras.backend import clear_session

In [2]:
main_folder = '../'   #main use
#main_folder = './'     #for debugging
dataset_folder = main_folder + 'dataset2/'
checkpoints_folder = main_folder + 'checkpoints_sect2/'
logs_folder = main_folder + 'logs/'

In [3]:
def load_tfrecord(filename, dataset_type=tf.int32):
    parse_tensor = lambda x: tf.io.parse_tensor(x, dataset_type)
    return tf.data.TFRecordDataset(filename).map(parse_tensor)
    
def make_tf_dataset(X, y, batch_size=32):
    #print(X.shape, y.shape)
    dataset = tf.data.Dataset.zip((X, y))
    dataset = dataset.batch(batch_size).prefetch(buffer_size=tf.data.AUTOTUNE)
    return dataset

In [4]:
def get_shape(dataset):
    print("c")
    for batch in dataset:
        print(batch)
        x,y = batch
        print("a")
        print(x.shape, y.shape)
        
def make_tf_dataset(X, y):
    dataset = tf.data.Dataset.zip((X, y))
    dataset = dataset.prefetch(buffer_size=tf.data.AUTOTUNE)
    get_shape(dataset)
    return dataset

In [5]:
X = load_tfrecord(dataset_folder + 'train_image_cropped.tfrecord', dataset_type=tf.double)
y = load_tfrecord(dataset_folder + 'train_label.tfrecord', dataset_type=tf.int64)

X_test = load_tfrecord(dataset_folder + 'test_image_cropped.tfrecord', dataset_type=tf.double)
y_test = load_tfrecord(dataset_folder + 'test_label.tfrecord', dataset_type=tf.int64)

In [6]:
X.take(1)

<TakeDataset element_spec=TensorSpec(shape=<unknown>, dtype=tf.float64, name=None)>

In [7]:
for batch, u in enumerate(X):
    print(batch, u)

0 tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   

In [8]:
X

<MapDataset element_spec=TensorSpec(shape=<unknown>, dtype=tf.float64, name=None)>

In [9]:
dataset = make_tf_dataset(X, y)

c
(<tf.Tensor: shape=(128, 42, 42, 1), dtype=float64, numpy=
array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
 

In [10]:
def get_shape(dataset):
    for batch in dataset:
        x,y = batch
        print(x.shape, y.shape)

In [11]:
get_shape(dataset)

(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
(128, 42, 42, 1) (128, 10)
